spring:
  # RDB properties
  datasource:
    url: jdbc:mysql://localhost:3306/hr                 # Mysql URL (??? DB ?? ??)
    username: root                                        # DB ??? ??
    password: qwer                                        # DB ????
    driver-class-name: com.mysql.cj.jdbc.Driver           # MariaDB ???? ??? ??

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

openapi:
  ktx:
    secret: ${ktx.secret}

logging:
  level:
    root: DEBUG
